// =======================================================
// This file is auto generated by [Convert Excel To .plist and .sqlite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  2016年8月15日 10:37:28
// ======================================================


#import "Models.h"

#pragma mark - 
@implementation TT_Project

@synthesize project_id = _project_id;
@synthesize name = _name;
@synthesize description = _description;
@synthesize is_private = _is_private;
@synthesize current_state = _current_state;
@synthesize is_allow_delete = _is_allow_delete;
@synthesize create_date = _create_date;
@synthesize create_user_id = _create_user_id;
@synthesize last_edit_date = _last_edit_date;
@synthesize last_edit_user_id = _last_edit_user_id;

- (NSString *)description
{
    NSLog(@"project_id:%@", _project_id);
    NSLog(@"name:%@", _name);
    NSLog(@"description:%@", _description);
    NSLog(@"is_private:%@", @(_is_private));
    NSLog(@"current_state:%@", @(_current_state));
    NSLog(@"is_allow_delete:%@", @(_is_allow_delete));
    NSLog(@"create_date:%@", _create_date);
    NSLog(@"create_user_id:%@", _create_user_id);
    NSLog(@"last_edit_date:%@", _last_edit_date);
    NSLog(@"last_edit_user_id:%@", _last_edit_user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Project_Members

@synthesize project_members_id = _project_members_id;
@synthesize project_id = _project_id;
@synthesize user_id = _user_id;

- (NSString *)description
{
    NSLog(@"project_members_id:%@", _project_members_id);
    NSLog(@"project_id:%@", _project_id);
    NSLog(@"user_id:%@", _user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Discuss

@synthesize discuss_id = _discuss_id;
@synthesize project_id = _project_id;
@synthesize discuss_type = _discuss_type;
@synthesize image_url = _image_url;
@synthesize content = _content;
@synthesize current_state = _current_state;
@synthesize is_allow_comment = _is_allow_comment;
@synthesize is_allow_delete = _is_allow_delete;
@synthesize create_date = _create_date;
@synthesize create_user_id = _create_user_id;
@synthesize last_edit_date = _last_edit_date;
@synthesize last_edit_user_id = _last_edit_user_id;

- (NSString *)description
{
    NSLog(@"discuss_id:%@", _discuss_id);
    NSLog(@"project_id:%@", _project_id);
    NSLog(@"discuss_type:%@", @(_discuss_type));
    NSLog(@"image_url:%@", _image_url);
    NSLog(@"content:%@", _content);
    NSLog(@"current_state:%@", @(_current_state));
    NSLog(@"is_allow_comment:%@", @(_is_allow_comment));
    NSLog(@"is_allow_delete:%@", @(_is_allow_delete));
    NSLog(@"create_date:%@", _create_date);
    NSLog(@"create_user_id:%@", _create_user_id);
    NSLog(@"last_edit_date:%@", _last_edit_date);
    NSLog(@"last_edit_user_id:%@", _last_edit_user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Discuss_Result

@synthesize discuss_result_id = _discuss_result_id;
@synthesize discuss_id = _discuss_id;
@synthesize discuss_result = _discuss_result;
@synthesize discuss_result_description = _discuss_result_description;

- (NSString *)description
{
    NSLog(@"discuss_result_id:%@", _discuss_result_id);
    NSLog(@"discuss_id:%@", _discuss_id);
    NSLog(@"discuss_result:%@", _discuss_result);
    NSLog(@"discuss_result_description:%@", _discuss_result_description);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Comment

@synthesize comment_id = _comment_id;
@synthesize discuss_id = _discuss_id;
@synthesize content = _content;
@synthesize image_url = _image_url;
@synthesize is_allow_delete = _is_allow_delete;
@synthesize create_date = _create_date;
@synthesize create_user_id = _create_user_id;
@synthesize last_edit_date = _last_edit_date;
@synthesize last_edit_user_id = _last_edit_user_id;

- (NSString *)description
{
    NSLog(@"comment_id:%@", _comment_id);
    NSLog(@"discuss_id:%@", _discuss_id);
    NSLog(@"content:%@", _content);
    NSLog(@"image_url:%@", _image_url);
    NSLog(@"is_allow_delete:%@", @(_is_allow_delete));
    NSLog(@"create_date:%@", _create_date);
    NSLog(@"create_user_id:%@", _create_user_id);
    NSLog(@"last_edit_date:%@", _last_edit_date);
    NSLog(@"last_edit_user_id:%@", _last_edit_user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_User

@synthesize user_id = _user_id;
@synthesize password = _password;
@synthesize name = _name;
@synthesize nick_name = _nick_name;
@synthesize wx_account = _wx_account;
@synthesize phone = _phone;
@synthesize head_img_url = _head_img_url;
@synthesize os_type = _os_type;
@synthesize os_description = _os_description;
@synthesize device_identify = _device_identify;
@synthesize create_date = _create_date;
@synthesize create_user_id = _create_user_id;
@synthesize last_edit_date = _last_edit_date;
@synthesize last_edit_user_id = _last_edit_user_id;

- (NSString *)description
{
    NSLog(@"user_id:%@", _user_id);
    NSLog(@"password:%@", _password);
    NSLog(@"name:%@", _name);
    NSLog(@"nick_name:%@", _nick_name);
    NSLog(@"wx_account:%@", _wx_account);
    NSLog(@"phone:%@", _phone);
    NSLog(@"head_img_url:%@", _head_img_url);
    NSLog(@"os_type:%@", _os_type);
    NSLog(@"os_description:%@", _os_description);
    NSLog(@"device_identify:%@", _device_identify);
    NSLog(@"create_date:%@", _create_date);
    NSLog(@"create_user_id:%@", _create_user_id);
    NSLog(@"last_edit_date:%@", _last_edit_date);
    NSLog(@"last_edit_user_id:%@", _last_edit_user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Notification

@synthesize notifiction_id = _notifiction_id;
@synthesize is_read = _is_read;
@synthesize content = _content;
@synthesize type = _type;
@synthesize is_removed = _is_removed;
@synthesize create_date = _create_date;
@synthesize create_user_id = _create_user_id;
@synthesize last_edit_date = _last_edit_date;
@synthesize last_edit_user_id = _last_edit_user_id;

- (NSString *)description
{
    NSLog(@"notifiction_id:%@", _notifiction_id);
    NSLog(@"is_read:%@", @(_is_read));
    NSLog(@"content:%@", _content);
    NSLog(@"type:%@", @(_type));
    NSLog(@"is_removed:%@", @(_is_removed));
    NSLog(@"create_date:%@", _create_date);
    NSLog(@"create_user_id:%@", _create_user_id);
    NSLog(@"last_edit_date:%@", _last_edit_date);
    NSLog(@"last_edit_user_id:%@", _last_edit_user_id);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_Attachment

@synthesize attachment_id = _attachment_id;
@synthesize current_item_id = _current_item_id;
@synthesize attachment_url = _attachment_url;
@synthesize attachment_content = _attachment_content;

- (NSString *)description
{
    NSLog(@"attachment_id:%@", _attachment_id);
    NSLog(@"current_item_id:%@", _current_item_id);
    NSLog(@"attachment_url:%@", _attachment_url);
    NSLog(@"attachment_content:%@", _attachment_content);

    return [super description];
}
@end

#pragma mark - 
@implementation TT_At_Members

@synthesize at_members_id = _at_members_id;
@synthesize current_item_id = _current_item_id;
@synthesize user_id = _user_id;

- (NSString *)description
{
    NSLog(@"at_members_id:%@", _at_members_id);
    NSLog(@"current_item_id:%@", _current_item_id);
    NSLog(@"user_id:%@", _user_id);

    return [super description];
}
@end